version: '3.8'
services:
  db:
    container_name: postGresConfeitaria
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./data-postgres/:/var/lib/postgres
